module.exports = {
    0: '0',
    hairline: 'var(--length-hairline)', // 1px
    0.25: 'calc(0.25 * var(--length-base))',
    0.5: 'calc(0.5 * var(--length-base))',
    0.75: 'calc(0.75 * var(--length-base))',
    1: 'calc(1.0 * var(--length-base))',
    1.5: 'calc(1.5 * var(--length-base))',
    2: 'calc(2.0 * var(--length-base))',
    2.5: 'calc(2.5 * var(--length-base))',
    3: 'calc(3.0 * var(--length-base))',
    4: 'calc(4.0 * var(--length-base))',
    5: 'calc(5.0 * var(--length-base))',
    6: 'calc(6.0 * var(--length-base))',
    8: 'calc(8.0 * var(--length-base))',
    10: 'calc(10.0 * var(--length-base))',
    12: 'calc(12.0 * var(--length-base))',
    14: 'calc(14.0 * var(--length-base))',
    16: 'calc(16.0 * var(--length-base))',
    18: 'calc(18.0 * var(--length-base))',
    20: 'calc(20.0 * var(--length-base))',
    24: 'calc(24.0 * var(--length-base))',
    28: 'calc(28.0 * var(--length-base))',
    30: 'calc(30.0 * var(--length-base))',
    32: 'calc(32.0 * var(--length-base))',
    36: 'calc(36.0 * var(--length-base))',
    40: 'calc(40.0 * var(--length-base))',
    48: 'calc(48.0 * var(--length-base))',
    56: 'calc(56.0 * var(--length-base))',
    64: 'calc(64.0 * var(--length-base))',
};
